"""baseline schema

Revision ID: e511dc25887f
Revises: 
Create Date: 2026-08-26 11:23:08.699898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e511dc25887f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_career_profile_target_career'), table_name='career_profile')
    op.drop_index(op.f('idx_career_recommendations_career'), table_name='career_recommendations')
    op.drop_index(op.f('idx_career_recommendations_user_id'), table_name='career_recommendations')
    op.drop_index(op.f('idx_career_score_snapshots_date'), table_name='career_score_snapshots')
    op.drop_index(op.f('idx_career_score_snapshots_user_id'), table_name='career_score_snapshots')
    op.drop_index(op.f('idx_job_matches_user_id'), table_name='job_matches')
    op.drop_index(op.f('idx_mentor_chats_user_id'), table_name='mentor_chats')
    op.drop_index(op.f('idx_notifications_user_id'), table_name='notifications')
    op.alter_column('project_recommendations', 'project_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('idx_project_recommendations_user_id'), table_name='project_recommendations')
    op.drop_index(op.f('idx_recommendation_feedback_user_id'), table_name='recommendation_feedback')
    op.drop_index(op.f('idx_resume_history_upload_date'), table_name='resume_history')
    op.drop_index(op.f('idx_resume_history_user_id'), table_name='resume_history')
    op.drop_index(op.f('idx_user_activity_created_at'), table_name='user_activity')
    op.drop_index(op.f('idx_user_activity_user_id'), table_name='user_activity')
    op.drop_index(op.f('idx_user_projects_completed_at'), table_name='user_projects')
    op.drop_index(op.f('idx_user_projects_user_completed'), table_name='user_projects')
    op.drop_index(op.f('idx_user_projects_user_id'), table_name='user_projects')
    op.drop_index(op.f('idx_user_skills_completed_at'), table_name='user_skills')
    op.drop_index(op.f('idx_user_skills_user_completed'), table_name='user_skills')
    op.drop_index(op.f('idx_user_skills_user_id'), table_name='user_skills')
    op.drop_index(op.f('idx_users_created_at'), table_name='users')
    op.drop_index(op.f('idx_users_role'), table_name='users')
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.create_index(op.f('idx_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('idx_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('idx_user_skills_user_id'), 'user_skills', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_skills_user_completed'), 'user_skills', ['user_id', 'completed', 'completed_at'], unique=False)
    op.create_index(op.f('idx_user_skills_completed_at'), 'user_skills', ['completed_at'], unique=False)
    op.create_index(op.f('idx_user_projects_user_id'), 'user_projects', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_projects_user_completed'), 'user_projects', ['user_id', 'completed', 'completed_at'], unique=False)
    op.create_index(op.f('idx_user_projects_completed_at'), 'user_projects', ['completed_at'], unique=False)
    op.create_index(op.f('idx_user_activity_user_id'), 'user_activity', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_activity_created_at'), 'user_activity', ['created_at'], unique=False)
    op.create_index(op.f('idx_resume_history_user_id'), 'resume_history', ['user_id'], unique=False)
    op.create_index(op.f('idx_resume_history_upload_date'), 'resume_history', ['upload_date'], unique=False)
    op.create_index(op.f('idx_recommendation_feedback_user_id'), 'recommendation_feedback', ['user_id'], unique=False)
    op.create_index(op.f('idx_project_recommendations_user_id'), 'project_recommendations', ['user_id'], unique=False)
    op.alter_column('project_recommendations', 'project_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('idx_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('idx_mentor_chats_user_id'), 'mentor_chats', ['user_id'], unique=False)
    op.create_index(op.f('idx_job_matches_user_id'), 'job_matches', ['user_id'], unique=False)
    op.create_index(op.f('idx_career_score_snapshots_user_id'), 'career_score_snapshots', ['user_id'], unique=False)
    op.create_index(op.f('idx_career_score_snapshots_date'), 'career_score_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('idx_career_recommendations_user_id'), 'career_recommendations', ['user_id'], unique=False)
    op.create_index(op.f('idx_career_recommendations_career'), 'career_recommendations', ['career'], unique=False)
    op.create_index(op.f('idx_career_profile_target_career'), 'career_profile', ['target_career'], unique=False)
    # ### end Alembic commands ###
